-- All operations in this migration are commented out because user_metrics does not exist at this point in the migration sequence.
-- ALTER TABLE user_metrics RENAME COLUMN user_id TO profile_id;
-- DROP POLICY IF EXISTS "Users can view their own metrics" ON user_metrics;
-- DROP POLICY IF EXISTS "Users can update their own metrics" ON user_metrics;
-- CREATE POLICY "Users can view their own metrics"
--     ON user_metrics
--     FOR SELECT
--     USING (auth.uid()::uuid = profile_id);
-- CREATE POLICY "Users can update their own metrics"
--     ON user_metrics
--     FOR UPDATE
--     USING (auth.uid()::uuid = profile_id); 